### ISSUE TITLE
[3.1] Events view notification clicked

### ISSUE THREAD

**Issue by Nokius** [DylanVanAssche/harbour-sailfinder#119]
When the user clicks on the notification about new message(s) or equal he will not be switched to the application.

**Comment by modulebaan** [comment]
Correct! I didn't know if anyone would use that :p 
Well, will add it in V3.1-14 after phone verification and release it then in the Store and Openrepos.

**Comment by Nokius** [comment]
I even tried to add visible and audible notification but it's not working :( 

it would be nice to have to see it also on the lock-screen save time to unlock the device for nothing :D

**Comment by modulebaan** [comment]
That's a Harbour restriction... I can't change the notification config file while not validating the Harbour rules.

**Comment by Nokius** [comment]
*ohh* okay then I need to hack on and fine a way to get it work when using harbour app and my changes :s

**Comment by modulebaan** [comment]
Oh are you working on Sailfinder?

**Comment by modulebaan** [comment]
If you use a config file from Jolla itself in /usr/share/lipstick/notifications then it works OK but it's restricted in Harbour to add new files their...

**Comment by Nokius** [comment]
I tried to add this file (local on my Jolla) but I didn't work I was also thinking about custom LED blinking something like red, but if this will block the client from approval meehh

**Comment by Nokius** [comment]
But woud it be possible to see the notification on the lock screen. At the moment I just see it in the events-view. It would be a nice to have if it's not possible by harbour rules okay

**Comment by modulebaan** [comment]
AFAIK it's not allowed by Harbour. It all depends on that config file

**Comment by modulebaan** [comment]
Done :)
Releasing now on Openrepos & Jolla Store

**Comment by Nokius** [comment]
The user is not able to remove the notification
if he long press the notification the x will popup but when the user press the x he get into the application

**Comment by modulebaan** [comment]
I will see what I can do about it but it's an issue with the signals provided by Jolla... Normally I would use onClicked but that one is never called when an user clicks on it. The onClosed signal is always called (clicked or closed)

**Comment by modulebaan** [comment]
I can't do this with the QML plugin so it has to stay this way... Maybe I will add a setting that allows the user to enable/disable the automatically open thingy?

**Comment by Nokius** [comment]
mmmhh

also the it's not counted if it's a message

**Comment by modulebaan** [comment]
I don't understand what you mean?

**Comment by Nokius** [comment]
if i get more then one message it's removing the older message notification and not adding the new one to have a list

**Comment by modulebaan** [comment]
Oh that's right... I haven't figured out yet how this works with the QML plugin...
