### ISSUE TITLE
[3.1] Send button is not anchored on the bottom of the page

### ISSUE THREAD

**Issue by Nokius** [DylanVanAssche/harbour-sailfinder#120]
The send button in the chat is not anchored to the bottom of the page.

When the user writes longer messages he is not able to send the text.
The workaround to use the highlighting is not working every time.

**Comment by modulebaan** [comment]
Will check it out :)
Probably for the 3.2 release...
How long (#lines) are we talking ?

**Comment by Nokius** [comment]
I'm talking about messages which are longer then 30 words.
At first the send button movies up and is over the match avatar on the right top, after writing more it's out of the page. I guess it's anchored on the top of the type-in element.

**Comment by modulebaan** [comment]
Yes it's anchored at the top. This is the result of using a Row {}.
Will convert this into an anchored QML file without the Row {} then it's OK.
