### ISSUE TITLE
[3.1] Enlarged picture in discovery presist after (dis-)liking 

### ISSUE THREAD

**Issue by Nokius** [DylanVanAssche/harbour-sailfinder#121]
If the user enlarged a picture and is pressing after that one of the three like options he will the the picture again when a new recommendation is visible.

**Comment by modulebaan** [comment]
Yep indeed, I should reset the url when the images were changed or just close the enlarged picture. Roadmap for 3.2

**Comment by Nokius** [comment]
it fades the enlarged image out when refreshing the page with the new recommendation, but it fades-in again when the new recommendation is loaded.
