### ISSUE TITLE
[3.1] Refresh recs when swipes are available again

### ISSUE THREAD

**Issue by Nokius** [DylanVanAssche/harbour-sailfinder#122]
The user need to restart to swipe again, after he run out of swipes. It looks like that the application is not restarting the recommendation fetch after the countdown (~12h) is down to 0.
Workaround is that the user restart after a while, I assume it's a bug coz there is a notification you can swipe again´ which makes sense with the expected behaviour.

**Comment by modulebaan** [comment]
Ok will add that signal in V3.2
