### ISSUE TITLE
[3.1] logging eats up GB of space.

### ISSUE THREAD

**Issue by Nokius** [DylanVanAssche/harbour-sailfinder#123]
During the last days my Deivce told me that it will soon will run out of free space. After a short research if I have to much audio files or other media file I spotted that the .cache folder is pretty will filed.

then I saw that `.cache/harbour-sailfinder/logging/` is using ~3GiB of space 😄 

Is it possible to add a garbage collection or to roll the logs after a specific amount of time 

Thanks in advance

**Comment by modulebaan** [comment]
Oops, there's a garbadge collecting thingy but it seems to be too lazy... Will fix that issue in V3.2

**Comment by modulebaan** [comment]
Will use [Sailthon](https://www.github.com/modulebaan/sailthon) to provide an default logging system for Python/QML applications on Sailfish OS. This will also fix this issue for Sailfinder and my other apps.
