### ISSUE TITLE
Authentication error (403)

### ISSUE THREAD

**Issue by wickedsp1d3r** [DylanVanAssche/harbour-sailfinder#131]
Hi,

Authentication ends up with an error `403`. No exact reason given.
The last lines from the log:

```
WARNING:Tinder token not found in JSON data
DEBUG:Starting new HTTPS connection (1): api.gotinder.com
DEBUG:https://api.gotinder.com:443 "POST /auth HTTP/1.1" 403 123
ERROR:HTTP POST server returned bad HTTP code: 403
```

A test request `POST /auth` with headers
```
Content-Type: application/json
User-Agent: Tinder/7.5.3 (iPhone; iOS 10.3.2; Scale/2.00)
```
and body
```
{
  "facebook_token": <ACCESS_TOKEN>,
  "facebook_id": <FACEBOOK_ID>
}
```
seems working. Source information can be found from [here](https://github.com/fbessez/Tinder).

Do you have any advice how this problem can be resolved with Sailfinder?
What could cause this?
Thanks!

Using SailfishOS 2.1.3.7 and latest Sailfinder.

**Comment by DylanVanAssche** [comment]
Tinder changed the API when moving towards their webapp. I'm currently finalizing [BeRail](https://www.github.com/irail/harbour-berail) and after that I will rewrite Sailfinder to use this new API with a C++ backend which will be more stable and faster then before.

The current version of Sailfinder uses an older version of the API (Tinder 4.x.x somewhere) which may be blocked by now.
