### ISSUE TITLE
Show matches their profile

### ISSUE THREAD

**Issue by ThomasBrixLarsen** [DylanVanAssche/harbour-sailfinder#142]
Got 4.0 from Warehouse.

Steps to reproduce:

Open a conversation with a match.

Nothing happens when clicking on profile picture and there is no menu to open the profile.

**Comment by DylanVanAssche** [comment]
That's not an issue it's just not implemented yet. This will be for a later version since I want to get the core version stable before adding more features to Sailfinder V4.0.

This was in the previous version possible but not yet in V4.0

**Comment by DylanVanAssche** [comment]
Fixed in V4.1!
