### ISSUE TITLE
Tinder authentication on Facebook error

### ISSUE THREAD

**Issue by lent0** [DylanVanAssche/harbour-sailfinder#160]
1. **What happens**: 
    - When authenticating Tinder on Facebook screen goes grey and there is text "Your popup is too small to display this page. Please enlarge it to proceed." 

![20180409232804](https://user-images.githubusercontent.com/38228419/38565553-4aa67b1e-3cea-11e8-9868-beb780be3e5e.jpg)

2. **What was expected**:
    - What's expected to happen

3. **How to reproduce**: 
    1. First time sign in to Facebook to authenticate Tinder

4. **Environment**: 
    - Sailfish OS version: 2.1.4.14
    - Sailfish OS hardware: Xperia X

**Comment by DylanVanAssche** [comment]
Thanks for the report! I experienced it as well since yesterday. Someone from the Jolla Store had this a couple weeks back already (seems to be rolled out in phases).

I will try to fix it ASAP since it's blocking all the things in Sailfinder :(

**Comment by DylanVanAssche** [comment]
Fixed 4.2
