### ISSUE TITLE
Login screen appearance in Jolla 1

### ISSUE THREAD

**Issue by ellidberg** [DylanVanAssche/harbour-sailfinder#161]
Hi,
as you requested in Jolla Store, I am uploading the screenshots of my Jolla 1. The appearance of the login and registration screens is somehow weird and the forms are shown only partly, so no text can be entered. I can place a marker in one of the text fields and the keyboard appears, but I cannot see anything which is typed. 
Hope this helps.
Cheers, dberg

![20180508123451](https://user-images.githubusercontent.com/39086087/39752840-f1c40ffa-52bc-11e8-832c-69763265a801.jpg)
![20180508123515](https://user-images.githubusercontent.com/39086087/39752841-f1dc8a4e-52bc-11e8-8387-d0058933703a.jpg)

**Comment by ellidberg** [comment]
Hey mate, sorry. Just checked now and found your update. Thank you, looks great!

**Comment by DylanVanAssche** [comment]
Yeah I found a fix :)
