### ISSUE TITLE
[3.X] Make updating job & school possible

### ISSUE THREAD

**Issue by DylanVanAssche** [DylanVanAssche/harbour-sailfinder#40]
Add more data to About for matches, however I receive a 404 error while other libraries like Pynder & TinderJS receive the correct data. The same happens when I try to update schools or jobs. I think it's related...

**Comment by modulebaan** [comment]
Will be added in Sailfinder V3.0
API is now accessible!

**Comment by modulebaan** [comment]
Postponed to V3.X
